### PR TITLE
fix(pingcap/tidb): update binary download script to use computed branch name

### LINKED ISSUE #3458: add CI params support for tidb pull_integration_e2e_test job
https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_integration_e2e_test

to support feature branch or other branches, let's give the room to given custom peer component repo branches.

### PR DESCRIPTION
**Pull request by wuhuizuo**
Close #3458

### CODE REVIEW

File: pipelines/pingcap/tidb/latest/pull_integration_e2e_test.groovy [hunk 1]
```diff
@@ -52,15 +52,18 @@ pipeline {
...
-                        sh label: 'download binary', script: """
-                            cd tests/integrationtest2 && ./download_integration_test_binaries.sh ${REFS.base_ref}
-                            ls -alh third_bin/
-                            ./third_bin/tikv-server -V
-                            ./third_bin/pd-server -V
-                            ./third_bin/tiflash --version
-                            ./third_bin/cdc version
-                        """
+                    script {
+                        def otherComponentBranch = component.computeBranchFromPR('other', REFS.base_ref, REFS.pulls[0].title, 'master')
```
Comment (wuhuizuo) [inline pipelines/pingcap/tidb/latest/pull_integration_e2e_test.groovy:56]:
```suggestion
                        // Computes the branch name for downloading binaries based on the PR target branch and title.
                        def otherComponentBranch = component.computeBranchFromPR('other', REFS.base_ref, REFS.pulls[0].title, 'master')
```
